### PR TITLE
Disable portal

### PR DESCRIPTION
**Pull request by curioussavage**
@jonnyboy0719 

Sorry to spam you this weekend...

### CODE REVIEW

**Comment by curioussavage** [comment]
Here is a screenshot of the current state of the webadmin page after this.
screen shot 2016-07-17 at 2 20 08 pm

**Comment by jonnyboy0719** [comment]
no worries, I'm just glad that my little plugin gets some needed updates heh :smile:

**Comment by curioussavage** [comment]
Oh I was going to say about this one. I think a major version bump might be in order. The change to the name of the ini file doesn't really break backwards compatibility but it does make it so you can't just upgrade and it works. Up to you though.

**Comment by jonnyboy0719** [comment]
that could be good tho, haven't done much for cuberite lately due I'm busy with my own game, heh.

**Comment by curioussavage** [comment]
Would you be opposed to me bumping to 3.0 and promoting my fork as the new
version? Or transferring ownership of the original repo? It would be nice
to be able to commit bug fixes to the main repo quickly.

**Comment by jonnyboy0719** [comment]
will do, can give you access. Just need to figure out how, will reply once that's done!

**Comment by jonnyboy0719** [comment]
I have now sent an invite your way, you only need to accept, then you should have full access! :+1:

**Pull request merged**
